// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbdtlsviafkbftjsxgpl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndiZHRsc3ZpYWZrYmZ0anN4Z3BsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzODg5NjIsImV4cCI6MjA1ODk2NDk2Mn0.5r6z6fVDJCAvVaf0yhshYm7juFO4DYpDDJCmjKNum9M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);